package com.system.internship.enums;

public enum RoleEnum {
  ROLE_STUDENT,
  ROLE_STAFF,
  ROLE_ADVISOR,
  ROLE_HEAD_INTERNSHIP_COORDINATOR,
  ROLE_DEPARTMENT_INTERNSHIP_COORDINATOR,
  ROLE_ADMINISTRATOR;
}
